// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import remarkNsDirectives from './src/plugins/remark-ns-directives.mjs';
import remarkBasePath from './src/plugins/remark-base-path.mjs';

/**
 * THE deployment prefix — single source of truth.
 *
 * Feeds Astro's own `base` AND remark-base-path, which prefixes every
 * root-relative link written in page content. Content is therefore authored
 * prefix-free (`/getting-started/quickstart-seek/`).
 *
 * CUSTOM-DOMAIN CUTOVER: set this to '' and `site` to
 * 'https://documentation.neuralseek.com', then add public/CNAME. Two things
 * the plugin cannot reach still need doing by hand — `hero.actions` links in
 * index.mdx (YAML frontmatter takes no expressions) and any raw <a href> in an
 * HTML block. Find them with:  grep -rn '"/ns-docs' src/content/
 */
const BASE = '/ns-docs';

// https://astro.build/config
export default defineConfig({
	// GitHub Pages project site.
	site: 'https://cerebralblue.github.io',
	base: BASE,
	// Astro CONCATENATES this array with Starlight's own remark plugins (user
	// entries first), so both run before Starlight's asides and neither
	// displaces them.
	//
	// ORDER MATTERS between these two: remark-base-path must see the AUTHORED
	// directive nodes so it can rewrite `href` attributes on `:::ns-card` /
	// `::ns-button`. remark-ns-directives rewrites those nodes into paragraphs,
	// after which the attributes are gone.
	markdown: {
		remarkPlugins: [[remarkBasePath, { base: BASE }], remarkNsDirectives],
	},
	integrations: [
		starlight({
			title: 'NeuralDocs',
			description: 'Official documentation for NeuralSeek — guides, reference, and how-tos.',
			lastUpdated: true,
			logo: {
				light: './src/assets/neuraldocs-logo-light.svg',
				dark: './src/assets/neuraldocs-logo-dark.svg',
				replacesTitle: true,
			},
			favicon: '/favicon.png',
			// One entry on purpose. The design system is ~19 files under
			// src/styles/, and their ORDER IS LOAD-BEARING (the CSS is unlayered,
			// so equal-specificity conflicts resolve by source order). That order
			// lives in src/styles/index.css, next to the CSS it orders — read its
			// header before adding, moving, or renumbering a file.
			customCss: ['./src/styles/index.css', './src/styles/18-chatbot.css'],
			components: {
				SocialIcons: './src/components/SocialIcons.astro',
				Footer: './src/components/Footer.astro',
				// Wraps Starlight's Hero to add the split code panel. Only
				// index.mdx has `hero:` frontmatter, so this is landing-page only.
				Hero: './src/components/Hero.astro',
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/CerebralBlue/ns-docs' },
			],
			// IA per planning/structure-sketch.md. The 8 top-level groups are the tree the team
			// approved; the gap-list audit (2026-08-04) was folded in as leaves and subgroups
			// rather than as new top-level groups, so the approved shape still holds.
			// Subtrees use explicit `items` rather than `autogenerate` so an overview page can
			// lead its group — autogenerate sorts alphabetically and would bury it mid-list.
			// `maistro/ntl` stays autogenerated: it is owned by the NTL doc generator.
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'What is NeuralSeek', slug: 'getting-started/what-is-neuralseek' },
						{ label: 'Quickstart: Seek', slug: 'getting-started/quickstart-seek' },
						{ label: 'Quickstart: mAIstro', slug: 'getting-started/quickstart-maistro' },
						{ label: 'Core concepts', slug: 'getting-started/concepts' },
						{ label: 'Onboarding wizard', slug: 'getting-started/onboarding-wizard' },
						{ label: 'How to get NeuralSeek', slug: 'getting-started/how-to-get-neuralseek' },
						// Deliberately the same page as Integrations > Overview: per Robert's review,
						// "what can we connect to?" belongs in the first section even as a duplicate link.
						{ label: 'What can we connect to?', slug: 'integrations/overview' },
					],
				},
				{
					label: 'Seek — Answering Questions',
					items: [
						{ label: 'Overview', slug: 'seek/overview' },
						{ label: 'Tuning answers', slug: 'seek/tuning' },
						{ label: 'Virtual KB', slug: 'seek/virtual-kb' },
						{ label: 'Dynamic filters', slug: 'seek/dynamic-filters' },
						{ label: 'Conversational context', slug: 'seek/conversational-context' },
						{ label: 'Caching', slug: 'seek/caching' },
						{ label: 'Personalization', slug: 'seek/personalization' },
						{ label: 'Answer curation', slug: 'seek/curation' },
						{ label: 'Chat client', slug: 'seek/chat-client' },
					],
				},
				{
					label: 'mAIstro — Agents & Workflows',
					items: [
						{ label: 'Overview', slug: 'maistro/overview' },
						{ label: 'Visual editor', slug: 'maistro/visual-editor' },
						{ label: 'Running & inspecting an agent', slug: 'maistro/inspector' },
						{ label: 'Agent Visualizer', slug: 'maistro/agent-visualizer' },
						{ label: 'Agent Registry', slug: 'maistro/agent-registry' },
						{ label: 'Agent Marketplace', slug: 'maistro/agent-marketplace' },
						{ label: 'Agent Scheduler', slug: 'maistro/agent-scheduler' },
						{ label: 'Run Agents', slug: 'maistro/run-agents' },
						{
							label: 'NeuralEdit',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'maistro/neuraledit/overview' },
								{ label: 'Context files', slug: 'maistro/neuraledit/context-files' },
								{ label: 'Editing & reviewing', slug: 'maistro/neuraledit/editing-and-reviewing' },
								{
									label: 'Authoring a NeuralEdit agent',
									slug: 'maistro/neuraledit/authoring-an-agent',
								},
							],
						},
						{ label: 'NTL overview', slug: 'maistro/ntl-overview' },
						{
							label: 'NTL Node Reference',
							collapsed: true,
							autogenerate: { directory: 'maistro/ntl' },
						},
					],
				},
				{
					label: 'Knowledge & Data',
					items: [
						{ label: 'Getting documents in', slug: 'knowledge/ingestion-overview' },
						{ label: 'Connect a knowledge base', slug: 'knowledge/connect-a-kb' },
						{ label: 'Supported knowledge bases', slug: 'knowledge/supported-knowledgebases' },
						{ label: 'Pinecone setup', slug: 'knowledge/pinecone' },
						{ label: 'Elasticsearch vector model', slug: 'knowledge/elasticsearch-vector-model' },
						{
							label: 'Hybrid, vector & semantic search',
							slug: 'knowledge/hybrid-vector-semantic-search',
						},
						{ label: 'Loading documents', slug: 'knowledge/load' },
						{ label: 'Extracting data', slug: 'knowledge/extract' },
						{ label: 'Document Manager', slug: 'knowledge/document-manager' },
						{ label: 'Table understanding', slug: 'knowledge/table-understanding' },
						{ label: 'Auto data cleanse', slug: 'knowledge/auto-data-cleanse' },
						{
							label: 'Managed KnowledgeBase',
							collapsed: true,
							items: [
								{ label: 'Overview', slug: 'knowledge/managed-knowledgebase/overview' },
								{ label: 'Web crawler', slug: 'knowledge/managed-knowledgebase/web-crawler' },
								{ label: 'Synonyms', slug: 'knowledge/managed-knowledgebase/synonyms' },
								{ label: 'KnowledgeBase API', slug: 'knowledge/managed-knowledgebase/kb-api' },
							],
						},
					],
				},
				{
					label: 'Integrations',
					items: [
						{ label: 'What can we connect to?', slug: 'integrations/overview' },
						{ label: 'Virtual agents', slug: 'integrations/virtual-agents' },
						{
							label: 'Virtual agent platforms',
							collapsed: true,
							items: [
								{
									label: 'watsonx Assistant',
									slug: 'integrations/virtual-agents/watsonx-assistant',
								},
								{ label: 'AWS Lex', slug: 'integrations/virtual-agents/aws-lex' },
								{ label: 'Kore.ai', slug: 'integrations/virtual-agents/kore-ai' },
							],
						},
						{ label: 'Training virtual agents', slug: 'integrations/training-virtual-agents' },
						{
							label: 'watsonx Assistant streaming',
							slug: 'integrations/watsonx-assistant-streaming',
						},
						{ label: 'NICE CXone', slug: 'integrations/nice-cxone' },
						{ label: 'Slack extension', slug: 'integrations/slack-extension' },
						{ label: 'Microsoft Teams extension', slug: 'integrations/teams-extension' },
						{ label: 'SharePoint sync', slug: 'integrations/sharepoint-sync' },
						{ label: 'MCP server', slug: 'integrations/mcp-server' },
						{ label: 'a2a server', slug: 'integrations/a2a-server' },
						{ label: 'Webhook', slug: 'integrations/webhook' },
						{ label: 'REST & Console APIs', slug: 'integrations/rest-and-console-api' },
						{ label: 'Chat SDK', slug: 'integrations/chat-sdk' },
						{ label: 'Implementing feedback', slug: 'integrations/feedback' },
					],
				},
				{
					label: 'Configuration',
					items: [
						{ label: 'Overview', slug: 'configuration/overview' },
						{
							label: 'Neural Config',
							collapsed: true,
							items: [
								{ label: 'Neural Config options', slug: 'configuration/neural-config' },
								{
									label: 'Using the Neural Config page',
									slug: 'configuration/neural-config/using-this-page',
								},
								{
									label: 'KnowledgeBase Connection',
									slug: 'configuration/neural-config/knowledgebase-connection',
								},
								{
									label: 'KnowledgeBase Tuning',
									slug: 'configuration/neural-config/knowledgebase-tuning',
								},
								{ label: 'LLM Details', slug: 'configuration/neural-config/llm-details' },
								{ label: 'Managed LLM Details', slug: 'configuration/neural-config/managed-llm' },
								{ label: 'Embedding models', slug: 'configuration/neural-config/embedding-models' },
								{
									label: 'mAIstro Configuration',
									slug: 'configuration/neural-config/maistro-configuration',
								},
								{
									label: 'Platform Preferences',
									slug: 'configuration/neural-config/platform-preferences',
								},
								{
									label: 'Prompt Engineering',
									slug: 'configuration/neural-config/prompt-engineering',
								},
								{
									label: 'Intent Matching & Cache',
									slug: 'configuration/neural-config/intent-matching-caching',
								},
								{ label: 'Secrets', slug: 'configuration/neural-config/secrets' },
							],
						},
						{ label: 'Supported LLMs', slug: 'configuration/supported-llms' },
						{ label: 'Multi-LLM', slug: 'configuration/multi-llm' },
						{ label: 'Multimodal', slug: 'configuration/multimodal' },
						{ label: 'Semantic model tuning', slug: 'configuration/semantic-model' },
						{ label: 'Language handling', slug: 'configuration/language' },
						{ label: 'Backup, restore & change logs', slug: 'configuration/backup-restore' },
						{
							label: 'Administration',
							collapsed: true,
							items: [
								{ label: 'API keys', slug: 'configuration/administration/api-keys' },
								{ label: 'Embed codes', slug: 'configuration/administration/embed-codes' },
								{
									label: 'Users & permissions',
									slug: 'configuration/administration/users-and-permissions',
								},
								{
									label: 'Default permissions',
									slug: 'configuration/administration/default-permissions',
								},
								{
									label: 'Self-hosting an LLM',
									slug: 'configuration/administration/self-hosting-an-llm',
								},
								{ label: 'Flex licensing', slug: 'configuration/administration/flex-licensing' },
								{ label: 'Support plans', slug: 'configuration/administration/support-plans' },
							],
						},
					],
				},
				{
					label: 'Governance & Analytics',
					items: [
						{ label: 'Overview', slug: 'governance/overview' },
						{
							label: 'Guardrails',
							collapsed: true,
							items: [
								{ label: 'Guardrails overview', slug: 'governance/guardrails/overview' },
								{ label: 'Profanity (HAP)', slug: 'governance/guardrails/profanity-hap' },
								{ label: 'Prompt injection', slug: 'governance/guardrails/prompt-injection' },
								{ label: 'Semantic scoring', slug: 'governance/guardrails/semantic-scoring' },
								{
									label: 'Attribution protection',
									slug: 'governance/guardrails/attribution-protection',
								},
								{ label: 'Minimum confidence', slug: 'governance/guardrails/min-confidence' },
								{
									label: 'Custom governance agents',
									slug: 'governance/guardrails/custom-governance-agents',
								},
							],
						},
						{
							label: 'Dashboards',
							collapsed: true,
							items: [
								{
									label: 'Reading the dashboards',
									slug: 'governance/analytics/reading-the-dashboards',
								},
								{ label: 'Seek overview', slug: 'governance/analytics/seek-overview' },
								{ label: 'Seek tokens & cost', slug: 'governance/analytics/seek-tokens-cost' },
								{
									label: 'Seek logs & configuration insights',
									slug: 'governance/analytics/seek-logs-and-config-insights',
								},
								{
									label: 'Agent insights & details',
									slug: 'governance/analytics/agent-insights-and-details',
								},
								{
									label: 'mAIstro logs, tokens & cost',
									slug: 'governance/analytics/agent-logs-tokens-cost',
								},
								{ label: 'Model comparison', slug: 'governance/analytics/model-comparison' },
								{ label: 'Custom dashboards', slug: 'governance/analytics/custom-dashboards' },
							],
						},
						{ label: 'PII detection', slug: 'governance/pii-detection' },
						{ label: 'Red team testing', slug: 'governance/red-team-testing' },
						{ label: 'Logging', slug: 'governance/logging' },
						{ label: 'Corporate document filter', slug: 'governance/corporate-document-filter' },
						{ label: 'Replay', slug: 'governance/replay' },
						{ label: 'Data security & privacy', slug: 'governance/data-security' },
						{ label: 'Semantic analytics', slug: 'governance/semantic-analytics' },
						{ label: 'Content analytics', slug: 'governance/content-analytics' },
						{ label: 'Sentiment', slug: 'governance/sentiment' },
						{ label: 'Intent categorization', slug: 'governance/intent-categorization' },
						{ label: 'Entity extraction', slug: 'governance/entity-extraction' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Changelog', slug: 'reference/changelog' },
						{ label: 'Deployment', slug: 'reference/deployment' },
						{ label: 'Plans & platforms', slug: 'reference/plans-and-platforms' },
					],
				},
			],
		}),
	],
});
